/* Generated by wayland-scanner 1.15.90 */

#ifndef ZWF_OUTPUT_MANAGEMENT_CLIENT_PROTOCOL_H
#define ZWF_OUTPUT_MANAGEMENT_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_zwf_output_management The zwf_output_management protocol
 * @section page_ifaces_zwf_output_management Interfaces
 * - @subpage page_iface_zwf_output_v1 - 
 * - @subpage page_iface_zwf_output_manager_v1 - 
 */
struct wl_output;
struct zwf_output_manager_v1;
struct zwf_output_v1;

/**
 * @page page_iface_zwf_output_v1 zwf_output_v1
 * @section page_iface_zwf_output_v1_api API
 * See @ref iface_zwf_output_v1.
 */
/**
 * @defgroup iface_zwf_output_v1 The zwf_output_v1 interface
 */
extern const struct wl_interface zwf_output_v1_interface;
/**
 * @page page_iface_zwf_output_manager_v1 zwf_output_manager_v1
 * @section page_iface_zwf_output_manager_v1_api API
 * See @ref iface_zwf_output_manager_v1.
 */
/**
 * @defgroup iface_zwf_output_manager_v1 The zwf_output_manager_v1 interface
 */
extern const struct wl_interface zwf_output_manager_v1_interface;

#define ZWF_OUTPUT_V1_SET_POSITION 0
#define ZWF_OUTPUT_V1_SET_MODE 1
#define ZWF_OUTPUT_V1_SET_TRANSFORM 2
#define ZWF_OUTPUT_V1_SET_SCALE 3


/**
 * @ingroup iface_zwf_output_v1
 */
#define ZWF_OUTPUT_V1_SET_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_zwf_output_v1
 */
#define ZWF_OUTPUT_V1_SET_MODE_SINCE_VERSION 1
/**
 * @ingroup iface_zwf_output_v1
 */
#define ZWF_OUTPUT_V1_SET_TRANSFORM_SINCE_VERSION 1
/**
 * @ingroup iface_zwf_output_v1
 */
#define ZWF_OUTPUT_V1_SET_SCALE_SINCE_VERSION 1

/** @ingroup iface_zwf_output_v1 */
static inline void
zwf_output_v1_set_user_data(struct zwf_output_v1 *zwf_output_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwf_output_v1, user_data);
}

/** @ingroup iface_zwf_output_v1 */
static inline void *
zwf_output_v1_get_user_data(struct zwf_output_v1 *zwf_output_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwf_output_v1);
}

static inline uint32_t
zwf_output_v1_get_version(struct zwf_output_v1 *zwf_output_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwf_output_v1);
}

/** @ingroup iface_zwf_output_v1 */
static inline void
zwf_output_v1_destroy(struct zwf_output_v1 *zwf_output_v1)
{
	wl_proxy_destroy((struct wl_proxy *) zwf_output_v1);
}

/**
 * @ingroup iface_zwf_output_v1
 */
static inline void
zwf_output_v1_set_position(struct zwf_output_v1 *zwf_output_v1, int32_t x, int32_t y)
{
	wl_proxy_marshal((struct wl_proxy *) zwf_output_v1,
			 ZWF_OUTPUT_V1_SET_POSITION, x, y);
}

/**
 * @ingroup iface_zwf_output_v1
 */
static inline void
zwf_output_v1_set_mode(struct zwf_output_v1 *zwf_output_v1, int32_t width, int32_t height, int32_t refresh)
{
	wl_proxy_marshal((struct wl_proxy *) zwf_output_v1,
			 ZWF_OUTPUT_V1_SET_MODE, width, height, refresh);
}

/**
 * @ingroup iface_zwf_output_v1
 */
static inline void
zwf_output_v1_set_transform(struct zwf_output_v1 *zwf_output_v1, uint32_t transform)
{
	wl_proxy_marshal((struct wl_proxy *) zwf_output_v1,
			 ZWF_OUTPUT_V1_SET_TRANSFORM, transform);
}

/**
 * @ingroup iface_zwf_output_v1
 */
static inline void
zwf_output_v1_set_scale(struct zwf_output_v1 *zwf_output_v1, wl_fixed_t scale)
{
	wl_proxy_marshal((struct wl_proxy *) zwf_output_v1,
			 ZWF_OUTPUT_V1_SET_SCALE, scale);
}

#define ZWF_OUTPUT_MANAGER_V1_GET_WF_OUTPUT 0


/**
 * @ingroup iface_zwf_output_manager_v1
 */
#define ZWF_OUTPUT_MANAGER_V1_GET_WF_OUTPUT_SINCE_VERSION 1

/** @ingroup iface_zwf_output_manager_v1 */
static inline void
zwf_output_manager_v1_set_user_data(struct zwf_output_manager_v1 *zwf_output_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwf_output_manager_v1, user_data);
}

/** @ingroup iface_zwf_output_manager_v1 */
static inline void *
zwf_output_manager_v1_get_user_data(struct zwf_output_manager_v1 *zwf_output_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwf_output_manager_v1);
}

static inline uint32_t
zwf_output_manager_v1_get_version(struct zwf_output_manager_v1 *zwf_output_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwf_output_manager_v1);
}

/** @ingroup iface_zwf_output_manager_v1 */
static inline void
zwf_output_manager_v1_destroy(struct zwf_output_manager_v1 *zwf_output_manager_v1)
{
	wl_proxy_destroy((struct wl_proxy *) zwf_output_manager_v1);
}

/**
 * @ingroup iface_zwf_output_manager_v1
 */
static inline struct zwf_output_v1 *
zwf_output_manager_v1_get_wf_output(struct zwf_output_manager_v1 *zwf_output_manager_v1, struct wl_output *output)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_constructor((struct wl_proxy *) zwf_output_manager_v1,
			 ZWF_OUTPUT_MANAGER_V1_GET_WF_OUTPUT, &zwf_output_v1_interface, NULL, output);

	return (struct zwf_output_v1 *) id;
}

#ifdef  __cplusplus
}
#endif

#endif
